import Foundation

struct ExerciseData {
    
    // Your custom exercises from backup
    static let customExercises: [(id: String, name: String, category: String, primaryMuscle: String, equipment: String, split: String)] = [
        ("custom_1770405770966", "Single Arm Cross Body Tricep Extension", "isolation", "triceps", "cable", "push"),
        ("custom_1770750204749", "Single arm kneeling lat pull", "isolation", "lats", "cable", "pull"),
        ("custom_1771177872844", "Cybex Abdominal Crunch", "isolation", "core", "machine", "core"),
        ("custom_pendulum_squat", "Pendulum Squat Machine", "compound", "quads", "machine", "legs"),
    ]
    
    static let defaultExercises: [(id: String, name: String, category: String, primaryMuscle: String, equipment: String, split: String)] = [
        
        // ==================== CHEST ====================
        ("barbell_bench_press", "Barbell Bench Press", "compound", "chest", "barbell", "push"),
        ("incline_barbell_bench_press", "Incline Barbell Bench Press", "compound", "chest", "barbell", "push"),
        ("decline_barbell_bench_press", "Decline Barbell Bench Press", "compound", "chest", "barbell", "push"),
        ("dumbbell_bench_press", "Dumbbell Bench Press", "compound", "chest", "dumbbell", "push"),
        ("incline_dumbbell_bench_press", "Incline Dumbbell Bench Press", "compound", "chest", "dumbbell", "push"),
        ("decline_dumbbell_bench_press", "Decline Dumbbell Bench Press", "compound", "chest", "dumbbell", "push"),
        ("dumbbell_fly", "Dumbbell Fly", "isolation", "chest", "dumbbell", "push"),
        ("incline_dumbbell_fly", "Incline Dumbbell Fly", "isolation", "chest", "dumbbell", "push"),
        ("decline_dumbbell_fly", "Decline Dumbbell Fly", "isolation", "chest", "dumbbell", "push"),
        ("cable_fly", "Cable Fly", "isolation", "chest", "cable", "push"),
        ("low_cable_fly", "Low to High Cable Fly", "isolation", "chest", "cable", "push"),
        ("high_cable_fly", "High to Low Cable Fly", "isolation", "chest", "cable", "push"),
        ("single_arm_cable_fly", "Single Arm Cable Fly", "isolation", "chest", "cable", "push"),
        ("chest_press_machine", "Chest Press Machine", "compound", "chest", "machine", "push"),
        ("incline_chest_press_machine", "Incline Chest Press Machine", "compound", "chest", "machine", "push"),
        ("decline_chest_press_machine", "Decline Chest Press Machine", "compound", "chest", "machine", "push"),
        ("pec_deck", "Pec Deck Machine", "isolation", "chest", "machine", "push"),
        ("smith_machine_bench_press", "Smith Machine Bench Press", "compound", "chest", "machine", "push"),
        ("smith_machine_incline_press", "Smith Machine Incline Press", "compound", "chest", "machine", "push"),
        ("dips", "Dips", "compound", "chest", "bodyweight", "push"),
        ("assisted_dip", "Assisted Dip Machine", "compound", "chest", "machine", "push"),
        ("push_up", "Push Up", "compound", "chest", "bodyweight", "push"),
        ("wide_push_up", "Wide Push Up", "compound", "chest", "bodyweight", "push"),
        ("close_grip_push_up", "Close Grip Push Up", "compound", "chest", "bodyweight", "push"),
        ("decline_push_up", "Decline Push Up", "compound", "chest", "bodyweight", "push"),
        ("incline_push_up", "Incline Push Up", "compound", "chest", "bodyweight", "push"),
        ("diamond_push_up", "Diamond Push Up", "compound", "chest", "bodyweight", "push"),
        ("plyometric_push_up", "Plyometric Push Up", "compound", "chest", "bodyweight", "push"),
        ("archer_push_up", "Archer Push Up", "compound", "chest", "bodyweight", "push"),
        ("floor_press", "Barbell Floor Press", "compound", "chest", "barbell", "push"),
        ("dumbbell_floor_press", "Dumbbell Floor Press", "compound", "chest", "dumbbell", "push"),
        ("single_arm_floor_press", "Single Arm Dumbbell Floor Press", "compound", "chest", "dumbbell", "push"),
        ("svend_press", "Svend Press", "isolation", "chest", "other", "push"),
        ("squeeze_press", "Dumbbell Squeeze Press", "compound", "chest", "dumbbell", "push"),
        ("around_the_world", "Dumbbell Around the World", "isolation", "chest", "dumbbell", "push"),
        ("pullover", "Dumbbell Pullover", "isolation", "chest", "dumbbell", "push"),
        ("cable_pullover", "Cable Pullover", "isolation", "chest", "cable", "push"),
        ("pullover_to_press", "Pullover to Press", "compound", "chest", "dumbbell", "push"),
        ("landmine_press", "Landmine Press", "compound", "chest", "barbell", "push"),
        ("single_arm_landmine_press", "Single Arm Landmine Press", "compound", "chest", "barbell", "push"),
        ("hex_press", "Hex Press", "compound", "chest", "dumbbell", "push"),
        
        // ==================== BACK ====================
        ("barbell_row", "Barbell Row", "compound", "back", "barbell", "pull"),
        ("pendlay_row", "Pendlay Row", "compound", "back", "barbell", "pull"),
        ("dumbbell_row", "Dumbbell Row", "compound", "back", "dumbbell", "pull"),
        ("single_arm_dumbbell_row", "Single Arm Dumbbell Row", "compound", "back", "dumbbell", "pull"),
        ("chest_supported_dumbbell_row", "Chest Supported Dumbbell Row", "compound", "back", "dumbbell", "pull"),
        ("incline_dumbbell_row", "Incline Dumbbell Row", "compound", "back", "dumbbell", "pull"),
        ("seal_row", "Seal Row", "compound", "back", "dumbbell", "pull"),
        ("seated_cable_row", "Seated Cable Row", "compound", "back", "cable", "pull"),
        ("single_arm_cable_row", "Single Arm Cable Row", "compound", "back", "cable", "pull"),
        ("face_pull_row", "Face Pull Row", "compound", "back", "cable", "pull"),
        ("t_bar_row", "T-Bar Row", "compound", "back", "barbell", "pull"),
        ("seated_row_machine", "Seated Row Machine", "compound", "back", "machine", "pull"),
        ("chest_supported_row_machine", "Chest Supported Row Machine", "compound", "back", "machine", "pull"),
        ("iso_lateral_row", "Iso-Lateral Row Machine", "compound", "back", "machine", "pull"),
        ("lat_pulldown", "Lat Pulldown", "compound", "lats", "cable", "pull"),
        ("wide_grip_lat_pulldown", "Wide Grip Lat Pulldown", "compound", "lats", "cable", "pull"),
        ("close_grip_lat_pulldown", "Close Grip Lat Pulldown", "compound", "lats", "cable", "pull"),
        ("reverse_grip_lat_pulldown", "Reverse Grip Lat Pulldown", "compound", "lats", "cable", "pull"),
        ("single_arm_lat_pulldown", "Single Arm Lat Pulldown", "compound", "lats", "cable", "pull"),
        ("straight_arm_pulldown", "Straight Arm Pulldown", "isolation", "lats", "cable", "pull"),
        ("pull_up", "Pull Up", "compound", "back", "bodyweight", "pull"),
        ("chin_up", "Chin Up", "compound", "back", "bodyweight", "pull"),
        ("wide_grip_pull_up", "Wide Grip Pull Up", "compound", "back", "bodyweight", "pull"),
        ("close_grip_pull_up", "Close Grip Pull Up", "compound", "back", "bodyweight", "pull"),
        ("neutral_grip_pull_up", "Neutral Grip Pull Up", "compound", "back", "bodyweight", "pull"),
        ("assisted_pull_up", "Assisted Pull Up", "compound", "back", "machine", "pull"),
        ("inverted_row", "Inverted Row", "compound", "back", "bodyweight", "pull"),
        ("deadlift", "Deadlift", "compound", "back", "barbell", "pull"),
        ("sumo_deadlift", "Sumo Deadlift", "compound", "back", "barbell", "pull"),
        ("romanian_deadlift", "Romanian Deadlift", "compound", "back", "barbell", "pull"),
        ("stiff_leg_deadlift", "Stiff Leg Deadlift", "compound", "back", "barbell", "pull"),
        ("trap_bar_deadlift", "Trap Bar Deadlift", "compound", "back", "barbell", "pull"),
        ("deficit_deadlift", "Deficit Deadlift", "compound", "back", "barbell", "pull"),
        ("rack_pull", "Rack Pull", "compound", "back", "barbell", "pull"),
        ("good_morning", "Good Morning", "compound", "back", "barbell", "pull"),
        ("back_extension", "Back Extension", "isolation", "back", "bodyweight", "pull"),
        ("hyperextension", "Hyperextension", "isolation", "back", "machine", "pull"),
        ("reverse_hyperextension", "Reverse Hyperextension", "isolation", "back", "machine", "pull"),
        ("meadows_row", "Meadows Row", "compound", "back", "barbell", "pull"),
        ("kroc_row", "Kroc Row", "compound", "back", "dumbbell", "pull"),
        ("helms_row", "Helms Row", "compound", "back", "dumbbell", "pull"),
        ("scapular_pull_up", "Scapular Pull-Up", "isolation", "back", "bodyweight", "pull"),
        ("muscle_up", "Muscle-Up", "compound", "lats", "bodyweight", "pull"),
        ("lat_pushdown", "Lat Pushdown", "isolation", "lats", "cable", "pull"),
        
        // ==================== SHOULDERS ====================
        ("overhead_press", "Barbell Overhead Press", "compound", "shoulders", "barbell", "push"),
        ("push_press", "Push Press", "compound", "shoulders", "barbell", "push"),
        ("dumbbell_shoulder_press", "Dumbbell Shoulder Press", "compound", "shoulders", "dumbbell", "push"),
        ("seated_dumbbell_shoulder_press", "Seated Dumbbell Shoulder Press", "compound", "shoulders", "dumbbell", "push"),
        ("arnold_press", "Arnold Press", "compound", "shoulders", "dumbbell", "push"),
        ("shoulder_press_machine", "Shoulder Press Machine", "compound", "shoulders", "machine", "push"),
        ("smith_machine_shoulder_press", "Smith Machine Shoulder Press", "compound", "shoulders", "machine", "push"),
        ("behind_neck_press", "Behind the Neck Press", "compound", "shoulders", "barbell", "push"),
        ("military_press", "Military Press (Strict)", "compound", "shoulders", "barbell", "push"),
        ("z_press", "Z Press", "compound", "shoulders", "barbell", "push"),
        ("landmine_shoulder_press", "Landmine Shoulder Press", "compound", "shoulders", "barbell", "push"),
        ("viking_press", "Viking Press Machine", "compound", "shoulders", "machine", "push"),
        ("dumbbell_lateral_raise", "Dumbbell Lateral Raise", "isolation", "shoulders", "dumbbell", "push"),
        ("cable_lateral_raise", "Cable Lateral Raise", "isolation", "shoulders", "cable", "push"),
        ("machine_lateral_raise", "Machine Lateral Raise", "isolation", "shoulders", "machine", "push"),
        ("leaning_lateral_raise", "Leaning Lateral Raise", "isolation", "shoulders", "dumbbell", "push"),
        ("incline_lateral_raise", "Incline Lateral Raise", "isolation", "shoulders", "dumbbell", "push"),
        ("front_raise", "Dumbbell Front Raise", "isolation", "shoulders", "dumbbell", "push"),
        ("cable_front_raise", "Cable Front Raise", "isolation", "shoulders", "cable", "push"),
        ("plate_front_raise", "Plate Front Raise", "isolation", "shoulders", "other", "push"),
        ("rear_delt_fly", "Rear Delt Fly", "isolation", "shoulders", "dumbbell", "pull"),
        ("cable_rear_delt_fly", "Cable Rear Delt Fly", "isolation", "shoulders", "cable", "pull"),
        ("rear_delt_machine", "Rear Delt Machine (Reverse Pec Deck)", "isolation", "shoulders", "machine", "pull"),
        ("face_pull", "Face Pull", "compound", "shoulders", "cable", "pull"),
        ("barbell_upright_row", "Barbell Upright Row", "compound", "shoulders", "barbell", "pull"),
        ("dumbbell_upright_row", "Dumbbell Upright Row", "compound", "shoulders", "dumbbell", "pull"),
        ("cable_upright_row", "Cable Upright Row", "compound", "shoulders", "cable", "pull"),
        ("barbell_shrug", "Barbell Shrug", "isolation", "shoulders", "barbell", "pull"),
        ("dumbbell_shrug", "Dumbbell Shrug", "isolation", "shoulders", "dumbbell", "pull"),
        ("trap_bar_shrug", "Trap Bar Shrug", "isolation", "shoulders", "barbell", "pull"),
        ("cable_shrug", "Cable Shrug", "isolation", "shoulders", "cable", "pull"),
        ("lu_raise", "Lu Raise", "isolation", "shoulders", "dumbbell", "push"),
        ("bus_driver", "Bus Driver", "isolation", "shoulders", "other", "push"),
        ("y_raise", "Y Raise", "isolation", "shoulders", "dumbbell", "pull"),
        ("prone_y_raise", "Prone Y Raise", "isolation", "shoulders", "dumbbell", "pull"),
        ("scott_press", "Scott Press", "compound", "shoulders", "dumbbell", "push"),
        
        // ==================== BICEPS ====================
        ("barbell_curl", "Barbell Curl", "isolation", "biceps", "barbell", "pull"),
        ("ez_bar_curl", "EZ Bar Curl", "isolation", "biceps", "barbell", "pull"),
        ("dumbbell_curl", "Dumbbell Curl", "isolation", "biceps", "dumbbell", "pull"),
        ("alternating_dumbbell_curl", "Alternating Dumbbell Curl", "isolation", "biceps", "dumbbell", "pull"),
        ("hammer_curl", "Hammer Curl", "isolation", "biceps", "dumbbell", "pull"),
        ("cross_body_hammer_curl", "Cross Body Hammer Curl", "isolation", "biceps", "dumbbell", "pull"),
        ("incline_dumbbell_curl", "Incline Dumbbell Curl", "isolation", "biceps", "dumbbell", "pull"),
        ("concentration_curl", "Concentration Curl", "isolation", "biceps", "dumbbell", "pull"),
        ("preacher_curl", "Preacher Curl", "isolation", "biceps", "barbell", "pull"),
        ("dumbbell_preacher_curl", "Dumbbell Preacher Curl", "isolation", "biceps", "dumbbell", "pull"),
        ("preacher_curl_machine", "Preacher Curl Machine", "isolation", "biceps", "machine", "pull"),
        ("cable_curl", "Cable Curl", "isolation", "biceps", "cable", "pull"),
        ("cable_hammer_curl", "Cable Hammer Curl (Rope)", "isolation", "biceps", "cable", "pull"),
        ("high_cable_curl", "High Cable Curl", "isolation", "biceps", "cable", "pull"),
        ("bayesian_cable_curl", "Bayesian Cable Curl", "isolation", "biceps", "cable", "pull"),
        ("machine_curl", "Machine Curl", "isolation", "biceps", "machine", "pull"),
        ("spider_curl", "Spider Curl", "isolation", "biceps", "dumbbell", "pull"),
        ("drag_curl", "Drag Curl", "isolation", "biceps", "barbell", "pull"),
        ("zottman_curl", "Zottman Curl", "isolation", "biceps", "dumbbell", "pull"),
        ("reverse_curl", "Reverse Curl", "isolation", "biceps", "barbell", "pull"),
        ("cable_reverse_curl", "Cable Reverse Curl", "isolation", "biceps", "cable", "pull"),
        ("waiter_curl", "Waiter Curl", "isolation", "biceps", "dumbbell", "pull"),
        ("21s_curl", "21s Curl", "isolation", "biceps", "barbell", "pull"),
        
        // ==================== TRICEPS ====================
        ("tricep_pushdown", "Tricep Pushdown", "isolation", "triceps", "cable", "push"),
        ("tricep_pushdown_rope", "Tricep Pushdown (Rope)", "isolation", "triceps", "cable", "push"),
        ("single_arm_tricep_pushdown", "Single Arm Tricep Pushdown", "isolation", "triceps", "cable", "push"),
        ("reverse_grip_pushdown", "Reverse Grip Pushdown", "isolation", "triceps", "cable", "push"),
        ("cable_overhead_tricep_extension", "Cable Overhead Tricep Extension", "isolation", "triceps", "cable", "push"),
        ("single_arm_overhead_extension", "Single Arm Overhead Extension", "isolation", "triceps", "cable", "push"),
        ("dumbbell_overhead_extension", "Dumbbell Overhead Extension", "isolation", "triceps", "dumbbell", "push"),
        ("skull_crusher", "Skull Crusher", "isolation", "triceps", "barbell", "push"),
        ("ez_bar_skull_crusher", "EZ Bar Skull Crusher", "isolation", "triceps", "barbell", "push"),
        ("dumbbell_skull_crusher", "Dumbbell Skull Crusher", "isolation", "triceps", "dumbbell", "push"),
        ("close_grip_bench_press", "Close Grip Bench Press", "compound", "triceps", "barbell", "push"),
        ("tricep_dip", "Tricep Dip", "compound", "triceps", "bodyweight", "push"),
        ("bench_dip", "Bench Dip", "compound", "triceps", "bodyweight", "push"),
        ("tricep_kickback", "Tricep Kickback", "isolation", "triceps", "dumbbell", "push"),
        ("cable_tricep_kickback", "Cable Tricep Kickback", "isolation", "triceps", "cable", "push"),
        ("jm_press", "JM Press", "compound", "triceps", "barbell", "push"),
        ("tate_press", "Tate Press", "isolation", "triceps", "dumbbell", "push"),
        ("french_press", "French Press", "isolation", "triceps", "barbell", "push"),
        ("machine_tricep_extension", "Machine Tricep Extension", "isolation", "triceps", "machine", "push"),
        ("bodyweight_tricep_extension", "Bodyweight Tricep Extension", "isolation", "triceps", "bodyweight", "push"),
        ("diamond_push_up_tricep", "Diamond Push Up (Triceps)", "compound", "triceps", "bodyweight", "push"),
        
        // ==================== QUADS ====================
        ("barbell_back_squat", "Barbell Back Squat", "compound", "quads", "barbell", "legs"),
        ("barbell_front_squat", "Barbell Front Squat", "compound", "quads", "barbell", "legs"),
        ("goblet_squat", "Goblet Squat", "compound", "quads", "dumbbell", "legs"),
        ("dumbbell_squat", "Dumbbell Squat", "compound", "quads", "dumbbell", "legs"),
        ("leg_press", "Leg Press", "compound", "quads", "machine", "legs"),
        ("single_leg_press", "Single Leg Press", "compound", "quads", "machine", "legs"),
        ("hack_squat", "Hack Squat Machine", "compound", "quads", "machine", "legs"),
        ("v_squat", "V Squat Machine", "compound", "quads", "machine", "legs"),
        ("pendulum_squat", "Pendulum Squat", "compound", "quads", "machine", "legs"),
        ("belt_squat", "Belt Squat", "compound", "quads", "machine", "legs"),
        ("smith_machine_squat", "Smith Machine Squat", "compound", "quads", "machine", "legs"),
        ("leg_extension", "Leg Extension", "isolation", "quads", "machine", "legs"),
        ("single_leg_extension", "Single Leg Extension", "isolation", "quads", "machine", "legs"),
        ("lunge", "Lunge", "compound", "quads", "bodyweight", "legs"),
        ("dumbbell_lunge", "Dumbbell Lunge", "compound", "quads", "dumbbell", "legs"),
        ("barbell_lunge", "Barbell Lunge", "compound", "quads", "barbell", "legs"),
        ("walking_lunge", "Walking Lunge", "compound", "quads", "dumbbell", "legs"),
        ("reverse_lunge", "Reverse Lunge", "compound", "quads", "dumbbell", "legs"),
        ("deficit_reverse_lunge", "Deficit Reverse Lunge", "compound", "quads", "dumbbell", "legs"),
        ("bulgarian_split_squat", "Bulgarian Split Squat", "compound", "quads", "dumbbell", "legs"),
        ("split_squat", "Split Squat", "compound", "quads", "bodyweight", "legs"),
        ("step_up", "Step-Up", "compound", "quads", "bodyweight", "legs"),
        ("dumbbell_step_up", "Dumbbell Step-Up", "compound", "quads", "dumbbell", "legs"),
        ("barbell_step_up", "Barbell Step-Up", "compound", "quads", "barbell", "legs"),
        ("box_squat", "Box Squat", "compound", "quads", "barbell", "legs"),
        ("pause_squat", "Pause Squat", "compound", "quads", "barbell", "legs"),
        ("sissy_squat", "Sissy Squat", "isolation", "quads", "bodyweight", "legs"),
        ("sissy_squat_machine", "Sissy Squat Machine", "isolation", "quads", "machine", "legs"),
        ("wall_sit", "Wall Sit", "isolation", "quads", "bodyweight", "legs"),
        ("pistol_squat", "Pistol Squat", "compound", "quads", "bodyweight", "legs"),
        ("zercher_squat", "Zercher Squat", "compound", "quads", "barbell", "legs"),
        ("safety_bar_squat", "Safety Bar Squat", "compound", "quads", "barbell", "legs"),
        ("spanish_squat", "Spanish Squat", "compound", "quads", "bands", "legs"),
        
        // ==================== HAMSTRINGS ====================
        ("romanian_deadlift_hamstring", "Romanian Deadlift", "compound", "hamstrings", "barbell", "legs"),
        ("dumbbell_romanian_deadlift", "Dumbbell Romanian Deadlift", "compound", "hamstrings", "dumbbell", "legs"),
        ("single_leg_romanian_deadlift", "Single Leg Romanian Deadlift", "compound", "hamstrings", "dumbbell", "legs"),
        ("stiff_leg_deadlift_hamstring", "Stiff Leg Deadlift", "compound", "hamstrings", "barbell", "legs"),
        ("lying_leg_curl", "Lying Leg Curl", "isolation", "hamstrings", "machine", "legs"),
        ("seated_leg_curl", "Seated Leg Curl", "isolation", "hamstrings", "machine", "legs"),
        ("standing_leg_curl", "Standing Leg Curl", "isolation", "hamstrings", "machine", "legs"),
        ("nordic_curl", "Nordic Curl", "isolation", "hamstrings", "bodyweight", "legs"),
        ("glute_ham_raise", "Glute Ham Raise", "compound", "hamstrings", "bodyweight", "legs"),
        ("cable_pull_through", "Cable Pull Through", "compound", "hamstrings", "cable", "legs"),
        ("kettlebell_swing", "Kettlebell Swing", "compound", "hamstrings", "other", "legs"),
        ("good_morning_hamstring", "Good Morning", "compound", "hamstrings", "barbell", "legs"),
        ("sliding_leg_curl", "Sliding Leg Curl", "isolation", "hamstrings", "bodyweight", "legs"),
        
        // ==================== GLUTES ====================
        ("barbell_hip_thrust", "Barbell Hip Thrust", "compound", "glutes", "barbell", "legs"),
        ("dumbbell_hip_thrust", "Dumbbell Hip Thrust", "compound", "glutes", "dumbbell", "legs"),
        ("single_leg_hip_thrust", "Single Leg Hip Thrust", "compound", "glutes", "bodyweight", "legs"),
        ("hip_thrust_machine", "Hip Thrust Machine", "compound", "glutes", "machine", "legs"),
        ("glute_bridge", "Glute Bridge", "compound", "glutes", "bodyweight", "legs"),
        ("barbell_glute_bridge", "Barbell Glute Bridge", "compound", "glutes", "barbell", "legs"),
        ("single_leg_glute_bridge", "Single Leg Glute Bridge", "compound", "glutes", "bodyweight", "legs"),
        ("cable_kickback", "Cable Kickback", "isolation", "glutes", "cable", "legs"),
        ("cable_pull_through_glute", "Cable Pull Through", "compound", "glutes", "cable", "legs"),
        ("donkey_kick", "Donkey Kick", "isolation", "glutes", "bodyweight", "legs"),
        ("fire_hydrant", "Fire Hydrant", "isolation", "glutes", "bodyweight", "legs"),
        ("clamshell", "Clamshell", "isolation", "glutes", "bodyweight", "legs"),
        ("frog_pump", "Frog Pump", "isolation", "glutes", "bodyweight", "legs"),
        ("sumo_squat", "Sumo Squat", "compound", "glutes", "dumbbell", "legs"),
        ("sumo_deadlift_glute", "Sumo Deadlift", "compound", "glutes", "barbell", "legs"),
        ("curtsy_lunge", "Curtsy Lunge", "compound", "glutes", "dumbbell", "legs"),
        ("glute_kickback_machine", "Glute Kickback Machine", "isolation", "glutes", "machine", "legs"),
        ("hip_abductor_machine", "Hip Abductor Machine", "isolation", "glutes", "machine", "legs"),
        ("hip_adductor_machine", "Hip Adductor Machine", "isolation", "glutes", "machine", "legs"),
        ("banded_lateral_walk", "Banded Lateral Walk", "isolation", "glutes", "bands", "legs"),
        ("banded_monster_walk", "Banded Monster Walk", "isolation", "glutes", "bands", "legs"),
        
        // ==================== CALVES ====================
        ("standing_calf_raise", "Standing Calf Raise", "isolation", "calves", "machine", "legs"),
        ("seated_calf_raise", "Seated Calf Raise", "isolation", "calves", "machine", "legs"),
        ("leg_press_calf_raise", "Leg Press Calf Raise", "isolation", "calves", "machine", "legs"),
        ("smith_machine_calf_raise", "Smith Machine Calf Raise", "isolation", "calves", "machine", "legs"),
        ("dumbbell_calf_raise", "Dumbbell Calf Raise", "isolation", "calves", "dumbbell", "legs"),
        ("single_leg_calf_raise", "Single Leg Calf Raise", "isolation", "calves", "bodyweight", "legs"),
        ("donkey_calf_raise", "Donkey Calf Raise", "isolation", "calves", "machine", "legs"),
        ("tibialis_raise", "Tibialis Raise", "isolation", "calves", "bodyweight", "legs"),
        ("calf_raise_on_step", "Calf Raise on Step", "isolation", "calves", "bodyweight", "legs"),
        
        // ==================== CORE ====================
        ("plank", "Plank", "isolation", "core", "bodyweight", "core"),
        ("side_plank", "Side Plank", "isolation", "core", "bodyweight", "core"),
        ("plank_shoulder_tap", "Plank Shoulder Tap", "isolation", "core", "bodyweight", "core"),
        ("dead_bug", "Dead Bug", "isolation", "core", "bodyweight", "core"),
        ("bird_dog", "Bird Dog", "isolation", "core", "bodyweight", "core"),
        ("crunch", "Crunch", "isolation", "core", "bodyweight", "core"),
        ("reverse_crunch", "Reverse Crunch", "isolation", "core", "bodyweight", "core"),
        ("bicycle_crunch", "Bicycle Crunch", "isolation", "core", "bodyweight", "core"),
        ("sit_up", "Sit Up", "isolation", "core", "bodyweight", "core"),
        ("decline_sit_up", "Decline Sit Up", "isolation", "core", "bodyweight", "core"),
        ("v_up", "V-Up", "isolation", "core", "bodyweight", "core"),
        ("toe_touch", "Toe Touch", "isolation", "core", "bodyweight", "core"),
        ("leg_raise", "Leg Raise", "isolation", "core", "bodyweight", "core"),
        ("hanging_leg_raise", "Hanging Leg Raise", "isolation", "core", "bodyweight", "core"),
        ("hanging_knee_raise", "Hanging Knee Raise", "isolation", "core", "bodyweight", "core"),
        ("toes_to_bar", "Toes to Bar", "isolation", "core", "bodyweight", "core"),
        ("ab_wheel_rollout", "Ab Wheel Rollout", "isolation", "core", "other", "core"),
        ("cable_crunch", "Cable Crunch", "isolation", "core", "cable", "core"),
        ("cable_woodchop", "Cable Woodchop", "isolation", "core", "cable", "core"),
        ("pallof_press", "Pallof Press", "isolation", "core", "cable", "core"),
        ("russian_twist", "Russian Twist", "isolation", "core", "bodyweight", "core"),
        ("mountain_climber", "Mountain Climber", "isolation", "core", "bodyweight", "core"),
        ("flutter_kick", "Flutter Kick", "isolation", "core", "bodyweight", "core"),
        ("scissor_kick", "Scissor Kick", "isolation", "core", "bodyweight", "core"),
        ("hollow_body_hold", "Hollow Body Hold", "isolation", "core", "bodyweight", "core"),
        ("l_sit", "L-Sit", "isolation", "core", "bodyweight", "core"),
        ("dragon_flag", "Dragon Flag", "isolation", "core", "bodyweight", "core"),
        ("ab_crunch_machine", "Ab Crunch Machine", "isolation", "core", "machine", "core"),
        ("farmers_walk", "Farmer's Walk", "compound", "core", "dumbbell", "core"),
        ("suitcase_carry", "Suitcase Carry", "compound", "core", "dumbbell", "core"),
        ("overhead_carry", "Overhead Carry", "compound", "core", "dumbbell", "core"),
        
        // ==================== FOREARMS ====================
        ("wrist_curl", "Wrist Curl", "isolation", "forearms", "dumbbell", "pull"),
        ("reverse_wrist_curl", "Reverse Wrist Curl", "isolation", "forearms", "dumbbell", "pull"),
        ("barbell_wrist_curl", "Barbell Wrist Curl", "isolation", "forearms", "barbell", "pull"),
        ("behind_back_wrist_curl", "Behind the Back Wrist Curl", "isolation", "forearms", "barbell", "pull"),
        ("farmers_walk_forearm", "Farmer's Walk", "compound", "forearms", "dumbbell", "pull"),
        ("plate_pinch", "Plate Pinch", "isolation", "forearms", "other", "pull"),
        ("dead_hang", "Dead Hang", "isolation", "forearms", "bodyweight", "pull"),
        ("gripper_squeeze", "Gripper Squeeze", "isolation", "forearms", "other", "pull"),
        ("fat_grip_training", "Fat Grip Training", "compound", "forearms", "other", "pull"),
        
        // ==================== FULL BODY / OLYMPIC ====================
        ("clean", "Clean", "compound", "back", "barbell", "pull"),
        ("power_clean", "Power Clean", "compound", "back", "barbell", "pull"),
        ("hang_clean", "Hang Clean", "compound", "back", "barbell", "pull"),
        ("snatch", "Snatch", "compound", "back", "barbell", "pull"),
        ("power_snatch", "Power Snatch", "compound", "back", "barbell", "pull"),
        ("hang_snatch", "Hang Snatch", "compound", "back", "barbell", "pull"),
        ("clean_and_jerk", "Clean and Jerk", "compound", "back", "barbell", "pull"),
        ("clean_and_press", "Clean and Press", "compound", "back", "barbell", "push"),
        ("thruster", "Barbell Thruster", "compound", "quads", "barbell", "legs"),
        ("dumbbell_thruster", "Dumbbell Thruster", "compound", "quads", "dumbbell", "legs"),
        ("kettlebell_thruster", "Kettlebell Thruster", "compound", "quads", "other", "legs"),
        ("box_jump", "Box Jump", "compound", "quads", "bodyweight", "legs"),
        ("squat_jump", "Squat Jump", "compound", "quads", "bodyweight", "legs"),
        ("split_squat_jump", "Split Squat Jump", "compound", "quads", "bodyweight", "legs"),
        ("broad_jump", "Broad Jump", "compound", "quads", "bodyweight", "legs"),
        ("burpee", "Burpee", "compound", "chest", "bodyweight", "push"),
        ("battle_rope_wave", "Battle Rope Wave", "compound", "shoulders", "other", "push"),
        ("sled_push", "Sled Push", "compound", "quads", "other", "legs"),
        ("sled_pull", "Sled Pull", "compound", "back", "other", "pull"),
        ("tire_flip", "Tire Flip", "compound", "back", "other", "pull"),
        ("dumbbell_snatch", "Dumbbell Snatch", "compound", "glutes", "dumbbell", "legs"),
        ("kettlebell_snatch", "Kettlebell Snatch", "compound", "glutes", "other", "legs"),
        ("kettlebell_clean", "Kettlebell Clean", "compound", "back", "other", "pull"),
        ("turkish_get_up", "Turkish Get Up", "compound", "core", "other", "core"),
    ]
    
    // Combined list
    static var allExercises: [(id: String, name: String, category: String, primaryMuscle: String, equipment: String, split: String)] {
        return defaultExercises + customExercises
    }
}
